/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-08 13:45:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.projectbbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>title</title>\r\n");
      out.write("<!-- Bootstrap cdn ì¤ì  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- carouselë¥¼ êµ¬ì±í  ìì­ ì¤ì  -->\r\n");
      out.write("<div style=\"width: 300px;margin: 100px;\">\r\n");
      out.write("<!-- carouselë¥¼ ì¬ì©íê¸° ìí´ìë classì carouselì slide ì¤ì íë¤. -->\r\n");
      out.write("<!-- carouselë í¹ì´íê² idë¥¼ ì¤ì í´ì¼ íë¤.-->\r\n");
      out.write("<div id=\"carousel-example-generic\" class=\"carousel slide\" >\r\n");
      out.write("<!-- carouselì ì§ìì -->\r\n");
      out.write("<!-- ì§ììë¼ê³ ë íëë° olíê·¸ì classì carousel-indicatorsë¥¼ ë£ëë¤. -->\r\n");
      out.write("<ol class=\"carousel-indicators\">\r\n");
      out.write("<!-- lië ì´ë¯¸ì§ ê°ìë§í¼ ì¶ê°íê³  data-targetì carousel idë¥¼ ê°ë¥´í¨ë¤. -->\r\n");
      out.write("<!-- data-slide-toë ììëë¡ 0ë¶í° ì¬ë¼ê°ê³  0ì activeë¥¼ ì¤ì íë¤. -->\r\n");
      out.write("<!-- ë±í ì´ ë¶ë¶ì ìµìë³ë¡ ì¤ì íê² ìë¤. -->\r\n");
      out.write("<li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("<li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\r\n");
      out.write("</ol>\r\n");
      out.write("<!-- ì¤ì  ì´ë¯¸ì§ ìì´í -->\r\n");
      out.write("<!-- classë carousel-innerë¡ ì¤ì íê³  roleì listboxìì ì¤ì íë¤. -->\r\n");
      out.write("<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("<!-- ì´ë¯¸ì§ì ê°ìë§í¼ itemì ë§ë ë¤. ì¤ìí í¬ì¸í¸ë carousel-indicatorsì li íê·¸ ê°ìì itemì ê°ìë ì¼ì¹í´ì¼ íë¤. -->\r\n");
      out.write("<div class=\"item active\">\r\n");
      out.write("<!-- ìë¯¸ì§ ì¤ì - -->\r\n");
      out.write("<img src=\"1.PNG\" style=\"width:100%\">\r\n");
      out.write("<!-- ìº¡ì ì¤ì  (ìëµ ê°ë¥) -->\r\n");
      out.write("<!-- ê¸ì ìì ê²ìì -->\r\n");
      out.write("<div class=\"carousel-caption\" style=\"color:black;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"item\">\r\n");
      out.write("<img src=\"b.PNG\" style=\"width:100%\">\r\n");
      out.write("<div class=\"carousel-caption\" style=\"color:black;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ì¼ìª½ íì´í ë²í¼ -->\r\n");
      out.write("<!-- hrefë carouselì idë¥¼ ê°ë¥´í¨ë¤. -->\r\n");
      out.write("<a class=\"left carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("<!-- ì¼ìª½ íì´í -->\r\n");
      out.write("<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("</a>\r\n");
      out.write("<!-- ì¤ë¥¸ìª½ íì´í ë²í¼ -->\r\n");
      out.write("<!-- hrefë carouselì idë¥¼ ê°ë¥´í¨ë¤. -->\r\n");
      out.write("<a class=\"right carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("<!-- ì¤ë¥¸ìª½ íì´í -->\r\n");
      out.write("<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("// ì´ë¯¸ì§ ì¬ë¼ì´ë ì»¨í¸ë¡¤ë¥¼ ì¬ì©íê¸° ìí´ìë carouselë¥¼ ì¤íí´ì¼íë¤.\r\n");
      out.write("$('#carousel-example-generic').carousel({\r\n");
      out.write("// ì¬ë¦¬ìë© ìë ìí ì§ì° ìê°\r\n");
      out.write("// falseë©´ ìë ìííì§ ìëë¤.\r\n");
      out.write("interval: 1000,\r\n");
      out.write("// hoverë¥¼ ì¤ì íë©´ ë§ì°ì¤ë¥¼ ê°ì ¸ëë©´ ìë ìíì´ ë©ì¶ë¤.\r\n");
      out.write("pause: \"hover\",\r\n");
      out.write("// ìí ì¤ì , trueë©´ 1 -> 2ê°ë©´ ë¤ì 1ë¡ ëìê°ì ë°ë³µ\r\n");
      out.write("wrap: true,\r\n");
      out.write("// í¤ë³´ë ì´ë²¤í¸ ì¤ì  ì¬ë¶(?)\r\n");
      out.write("keyboard : true\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("window.onfocus=function(){\r\n");
      out.write("}\r\n");
      out.write("window.onload=function(){\r\n");
      out.write(" window.focus(); // íì¬ window ì¦ ìµì¤íë¬ë¬ë¥¼ ìëì° ìµìë¨ì ìì¹\r\n");
      out.write("window.moveTo(0,0); // ì¹ íì´ì§ì ì°½ ìì¹ë¥¼ 0,0 (ì¼ìª½ ìµìë¨) ì¼ë¡ ê³ ì \r\n");
      out.write("window.resizeTo(640,480); // ì¹íì´ì§ì í¬ê¸°ë¥¼ ê°ë¡ 1280 , ì¸ë¡ 800 ì¼ë¡ ê³ ì (íì¥ ë° ì¶ì)\r\n");
      out.write("window.scrollTo(0,250); // íì´ì§ ìë¨ ê´ê³ ë¥¼ ë°ë¡ ë³¼ ì ìê² ì¤í¬ë¡¤ ìì¹ë¥¼ ì¡°ì \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
